// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsjsxpicclqrpztpfeqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzanN4cGljY2xxcnB6dHBmZXFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NTkyODEsImV4cCI6MjA2ODIzNTI4MX0.AlVYnQO2jSva8p7ymjFfII5MfQf9WT20MIbKXlM7MXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});